[profile.default]
src = "src"
out = "out"
libs = ["lib"]
extra_output = ['devdoc', 'userdoc', 'metadata', 'storageLayout']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
]

[fmt]
bracket_spacing = true
line_length = 80
multiline_func_header = 'all'
number_underscore = 'thousands'
wrap_comments = true



[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
optimism = "https://rpc.ankr.com/optimism"
fantom = "https://rpc.ankr.com/fantom"
arbitrum = "https://rpc.ankr.com/arbitrum"
bsc = "https://bsc-dataseed.binance.org/"
moonriver = "https://moonriver.public.blastapi.io"
gnosis = "https://rpc.ankr.com/gnosis"
avax = "https://rpc.ankr.com/avalanche"
polygon = "https://rpc.ankr.com/polygon"
sepolia = "${SEPOLIA_RPC_URL}"


private_key="${ENV_PRIVATE_KEY}"